// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartGridAPI.Data;

#nullable disable

namespace SmartGridAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260717092220_AddUserIdToTeamMember")]
    partial class AddUserIdToTeamMember
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartGridAPI.Models.EnergyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Current")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Frequency")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MeterId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PowerFactor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Production")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Voltage")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("NodeId", "Timestamp");

                    b.ToTable("EnergyReadings");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Consumption = 120m,
                            Current = 15m,
                            Frequency = 50m,
                            NodeId = 1,
                            PowerFactor = 0.95m,
                            Production = 0m,
                            Timestamp = new DateTime(2026, 7, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Voltage = 220m
                        },
                        new
                        {
                            Id = 102,
                            Consumption = 150m,
                            Current = 20m,
                            Frequency = 50m,
                            NodeId = 2,
                            PowerFactor = 0.92m,
                            Production = 50m,
                            Timestamp = new DateTime(2026, 7, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Voltage = 215m
                        },
                        new
                        {
                            Id = 103,
                            Consumption = 80m,
                            Current = 10m,
                            Frequency = 50m,
                            NodeId = 3,
                            PowerFactor = 0.98m,
                            Production = 0m,
                            Timestamp = new DateTime(2026, 7, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Voltage = 230m
                        },
                        new
                        {
                            Id = 104,
                            Consumption = 125m,
                            Current = 16m,
                            Frequency = 50m,
                            NodeId = 1,
                            PowerFactor = 0.94m,
                            Production = 0m,
                            Timestamp = new DateTime(2026, 6, 30, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Voltage = 225m
                        },
                        new
                        {
                            Id = 105,
                            Consumption = 160m,
                            Current = 22m,
                            Frequency = 50m,
                            NodeId = 2,
                            PowerFactor = 0.90m,
                            Production = 40m,
                            Timestamp = new DateTime(2026, 6, 30, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Voltage = 210m
                        },
                        new
                        {
                            Id = 106,
                            Consumption = 75m,
                            Current = 9m,
                            Frequency = 50m,
                            NodeId = 3,
                            PowerFactor = 0.99m,
                            Production = 0m,
                            Timestamp = new DateTime(2026, 6, 29, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Voltage = 235m
                        },
                        new
                        {
                            Id = 107,
                            Consumption = 135m,
                            Current = 18m,
                            Frequency = 50m,
                            NodeId = 1,
                            PowerFactor = 0.93m,
                            Production = 0m,
                            Timestamp = new DateTime(2026, 6, 28, 15, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1,
                            Voltage = 218m
                        });
                });

            modelBuilder.Entity("SmartGridAPI.Models.Fault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIPrediction")
                        .HasColumnType("longtext");

                    b.Property<string>("AIRecommendation")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("FaultType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("NodeId", "Status");

                    b.ToTable("Faults");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "Transformer Oil Leak",
                            FaultType = "",
                            NodeId = 1,
                            ReportedAt = new DateTime(2026, 7, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReportedByUserId = 1,
                            Severity = "Critical",
                            Status = "Reported"
                        },
                        new
                        {
                            Id = 102,
                            Description = "Voltage Sag",
                            FaultType = "",
                            NodeId = 2,
                            ReportedAt = new DateTime(2026, 7, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            ReportedByUserId = 1,
                            Severity = "Medium",
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Phase Imbalance",
                            FaultType = "",
                            NodeId = 3,
                            ReportedAt = new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            ReportedByUserId = 1,
                            Severity = "High",
                            Status = "Reported"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Broken Insulator",
                            FaultType = "",
                            NodeId = 4,
                            ReportedAt = new DateTime(2026, 6, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            ReportedByUserId = 1,
                            ResolvedAt = new DateTime(2026, 6, 30, 20, 0, 0, 0, DateTimeKind.Utc),
                            Severity = "Low",
                            Status = "Resolved"
                        });
                });

            modelBuilder.Entity("SmartGridAPI.Models.GridNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<decimal?>("MaxCapacity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("GridNodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 40.712800000000001,
                            Location = "Downtown Substation",
                            Longitude = -74.006,
                            MaxCapacity = 5000m,
                            NodeId = "NODE-001",
                            NodeType = "Substation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 40.758000000000003,
                            Location = "Industrial Zone",
                            Longitude = -73.985500000000002,
                            MaxCapacity = 3000m,
                            NodeId = "NODE-002",
                            NodeType = "Distribution",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 40.783099999999997,
                            Location = "Residential Area North",
                            Longitude = -73.971199999999996,
                            MaxCapacity = 1500m,
                            NodeId = "NODE-003",
                            NodeType = "Feeder",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 40.748399999999997,
                            Location = "Commercial District",
                            Longitude = -73.996700000000004,
                            MaxCapacity = 2500m,
                            NodeId = "NODE-004",
                            NodeType = "Distribution",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 40.728200000000001,
                            Location = "Eastern Substation",
                            Longitude = -73.794899999999998,
                            MaxCapacity = 4000m,
                            NodeId = "NODE-005",
                            NodeType = "Substation",
                            Status = "Maintenance"
                        });
                });

            modelBuilder.Entity("SmartGridAPI.Models.MaintenanceTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TeamId");

                    b.ToTable("MaintenanceTeams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Latitude = 11.1271,
                            Longitude = 78.656899999999993,
                            Phone = "9876543210",
                            Status = "Available",
                            TeamName = "Team A"
                        },
                        new
                        {
                            TeamId = 2,
                            Latitude = 11.35,
                            Longitude = 78.900000000000006,
                            Phone = "9876543211",
                            Status = "Busy",
                            TeamName = "Team B"
                        },
                        new
                        {
                            TeamId = 3,
                            Latitude = 11.199999999999999,
                            Longitude = 78.75,
                            Phone = "9876543212",
                            Status = "Available",
                            TeamName = "Team C"
                        });
                });

            modelBuilder.Entity("SmartGridAPI.Models.MaintenanceTeamMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.HasIndex("TeamId");

                    b.ToTable("MaintenanceTeamMembers");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Name = "Lead Engineer",
                            PhoneNumber = "+919344255537",
                            Role = "Senior Engineer",
                            TeamId = 1
                        },
                        new
                        {
                            MemberId = 2,
                            Name = "Technician John",
                            PhoneNumber = "+919876543211",
                            Role = "Technician",
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("SmartGridAPI.Models.MaintenanceTicket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AcceptedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FaultId")
                        .HasColumnType("int");

                    b.Property<string>("ProofPhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("FaultId");

                    b.HasIndex("TeamId");

                    b.ToTable("MaintenanceTickets");
                });

            modelBuilder.Entity("SmartGridAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartGridAPI.Models.Outage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIAnalysis")
                        .HasColumnType("longtext");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AffectedArea")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("AffectedCustomers")
                        .HasColumnType("int");

                    b.Property<string>("Cause")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("EstimatedRestorationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<string>("OutageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "Status");

                    b.ToTable("Outages");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            AffectedArea = "",
                            AffectedCustomers = 450,
                            NodeId = 2,
                            OutageType = "Unplanned",
                            StartedAt = new DateTime(2026, 7, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Ongoing"
                        },
                        new
                        {
                            Id = 102,
                            AffectedArea = "",
                            AffectedCustomers = 1200,
                            NodeId = 5,
                            OutageType = "Unplanned",
                            RestoredAt = new DateTime(2026, 6, 30, 18, 0, 0, 0, DateTimeKind.Utc),
                            StartedAt = new DateTime(2026, 6, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Restored"
                        });
                });

            modelBuilder.Entity("SmartGridAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@smartgrid.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$t3KQzl4lh40owPIXHkxXCOJpfYSMIvH/YF6CygLub4220I5GMGXnm",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "officer@smartgrid.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$t3KQzl4lh40owPIXHkxXCOJpfYSMIvH/YF6CygLub4220I5GMGXnm",
                            Role = "Electricity Officer",
                            Username = "electricity_officer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "team@smartgrid.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$t3KQzl4lh40owPIXHkxXCOJpfYSMIvH/YF6CygLub4220I5GMGXnm",
                            Role = "Maintenance Team",
                            Username = "maintenance_team"
                        });
                });

            modelBuilder.Entity("SmartGridAPI.Models.EnergyReading", b =>
                {
                    b.HasOne("SmartGridAPI.Models.GridNode", "Node")
                        .WithMany("EnergyReadings")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartGridAPI.Models.User", "User")
                        .WithMany("EnergyReadings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartGridAPI.Models.Fault", b =>
                {
                    b.HasOne("SmartGridAPI.Models.GridNode", "Node")
                        .WithMany("Faults")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartGridAPI.Models.User", "ReportedBy")
                        .WithMany("FaultReports")
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("SmartGridAPI.Models.MaintenanceTeamMember", b =>
                {
                    b.HasOne("SmartGridAPI.Models.MaintenanceTeam", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SmartGridAPI.Models.MaintenanceTicket", b =>
                {
                    b.HasOne("SmartGridAPI.Models.Fault", "Fault")
                        .WithMany()
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartGridAPI.Models.MaintenanceTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fault");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SmartGridAPI.Models.Outage", b =>
                {
                    b.HasOne("SmartGridAPI.Models.GridNode", "Node")
                        .WithMany("Outages")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("SmartGridAPI.Models.GridNode", b =>
                {
                    b.Navigation("EnergyReadings");

                    b.Navigation("Faults");

                    b.Navigation("Outages");
                });

            modelBuilder.Entity("SmartGridAPI.Models.MaintenanceTeam", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SmartGridAPI.Models.User", b =>
                {
                    b.Navigation("EnergyReadings");

                    b.Navigation("FaultReports");
                });
#pragma warning restore 612, 618
        }
    }
}
